# Generated by Django 4.1 on 2022-09-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APITodolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasktitle', models.CharField(max_length=30)),
                ('taskDesc', models.TextField()),
                ('checked', models.BooleanField(default=False)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
